### ISSUE TITLE
Estimation error

### ISSUE THREAD

**Issue by DenisSergeevitch** [RobertGawron/supper-resolution#17]
```
python3 ./SRRestorer.py /Users/pro16/Dropbox/Terminal/supper-resolution-master/input/
Estimate Motion Between Sample And Original Image
Restore SR Image
Creating Camera Model
Size Of Estimated Original: 420x520
 0: estimation error: 14.838214
 1: estimation error: 14.335206
 2: estimation error: 13.815206
```

Every time after running I have the same problem, please add some more information for this error describing. 

Source image in /input folder is [this](https://www.dropbox.com/s/0iczng70wk3l5f6/circuit.tif?dl=0).

**Comment by jmtaysom** [comment]
Denis, those are the reported estimation error of that has been calculated by the script. They are not in the sense that something went wrong. If you keep letting it run it will finish eventually.
