### ISSUE TITLE
list out of index

### ISSUE THREAD

**Issue by sanjaykurali16** [RobertGawron/supper-resolution#18]
Traceback (most recent call last):
  File "SRRestorer.py", line 153, in <module>
    origSizeX = samples[0][1].size[1] * scale 
IndexError: list index out of range
![5](https://cloud.githubusercontent.com/assets/25748042/25935042/acc460c6-363e-11e7-9970-9ffab79ee689.jpg)

**Comment by sanjaykurali16** [comment]
can qr code part be enhanced to scan it??

**Comment by adwin5** [comment]
@sanjaykurali16 you should use .tif format
